[package]
name = "ensure_no_std"
version = "0.1.0"
authors = ["Yevhenii Babichenko <eugene.babichenko@protonmail.com>"]
edition = "2018"

[dependencies]
rust-fsm = { path = "..", default-features = false }
